### ISSUE TITLE
Incorrect detection of short-form function

### ISSUE THREAD

**Issue by fredrikekre** [fredrikekre/highlight.js#1]
```
@test Array(a) .+ Array(b) == Array(c)
```
from https://juliagpu.org/2020-11-05-oneapi_0.1/:
![Screenshot from 2020-11-06 15-39-50](https://user-images.githubusercontent.com/11698744/98379161-478b2400-2047-11eb-8259-ac4a6618ddc1.png)

**Comment by fredrikekre** [comment]
fixed by 87304ed30fae92a803e0ea2fbe7b7d7e13c3a91c

**Comment by fredrikekre** [comment]
cc @maleadt

**Comment by maleadt** [comment]
Awesome, thanks! Deployed to https://juliagpu.org/2020-11-05-oneapi_0.1/#kernel-programming, looks better now :-)
EDIT: although I seem to have lost some other highlighting...
